### ISSUE TITLE
ReferenceError: Buffer is not defined

### ISSUE THREAD

**Issue by doonv** [janispritzkau/nbt-ts#7]
I'm trying to use this library in my Svelte app, but I keep getting the error `Uncaught (in promise) ReferenceError: Buffer is not defined`.

From my research it seems `Buffer` is a node-only thing, and I can't use that.

What could I do to make this work?

**Comment by janispritzkau** [comment]
Sorry for the late reply. While I originally intended this library to be used only for Node.js, you could polyfill Node's Buffer. Of course, it depends on your build system how you would do this. Although if I were to redo this library, I'd use Uint8Array.
